
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda handler for API Gateway - Twilio integration
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayApi
        - .execute-api.
        - Ref: AWS::Region
        - .amazonaws.com/prod
Resources:
  ApiGatewayApi:
    Properties:
      DefinitionUri: s3://gg-18-lambda-deploy/swagger.yaml
      StageName: prod
      Variables:
        LambdaFunctionName:
          Ref: LambdaFunction
    Type: AWS::Serverless::Api
  LambdaFunction:
    Properties:
      CodeUri: s3://gg-18-lambda-deploy/lambda_function.zip
      Description: Lambda handler for API Gateway - Twilio integration
      Events:
        AddPhotoApi:
          Properties:
            Method: GET
            Path: /send-message
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Runtime: python2.7
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31